# -*- coding: utf-8 -*-
"""Day10_Ex1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uq1oWmFJ4d6G03RfCr5hqBV5oigWU8_A
"""

import cv2
import numpy as np
from matplotlib import pyplot as plt

img = cv2.imread('koala.JPG',0)

plt.imshow(img,cmap = 'gray')
print(img.shape)

img_f = np.fft.fft2(img)
fshift = np.fft.fftshift(img_f)
magnitude_img = 20*np.log(np.abs(fshift))

plt.imshow(magnitude_img,cmap='gray')

rows, cols = img.shape
crow, ccol = rows/2 , cols/2

mask = np.zeros((rows,cols,2),np.uint8)

mask[int(crow-30): int(crow+30), int(ccol-30): int(ccol+30)] = 1

dft = cv2.dft(np.float32(img),flags = cv2.DFT_COMPLEX_OUTPUT)

dft_shift = np.fft.fftshift(dft)

fshift = dft_shift*mask

f_ishift= np.fft.ifftshift(fshift)

img_back = cv2.idft(f_ishift)

plt.imshow(img_back[:,:,0],cmap='gray')